#!/bin/bash

AWS_S3_ACCESS_KEY_ID=${AWS_S3_ACCESS_KEY_ID:-${ACCESS_KEY_ID}}
AWS_S3_SECRET_ACCESS_KEY=${AWS_S3_SECRET_ACCESS_KEY:-${SECRET_ACCESS_KEY}}
AWS_S3_URL=${AWS_S3_URL:-${URL}}
AWS_S3_BUCKET=${AWS_S3_BUCKET:-${BUCKET}}
AWS_S3_MOUNT=${AWS_S3_MOUNT:-${MOUNT}}

/usr/bin/docker-entrypoint.sh &
/usr/bin/nfsd.sh